services:
  mysqldb:
    image: mysql
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: urlsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      SERVICES_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - mynetwork
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'password'
      DB_NAME: urlsdb
      DB_CONNECTION_LIMIT: 20
      SERVICES_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 3000
    networks:
      - mynetwork
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysqldb

networks:
  mynetwork:
    driver: bridge